Generate virtual player
jczestochowska/probabilistic_learning_task pull request #10
Opened 2018-04-10 17:50 UTC by kcwojdzinska

2018-04-14 13:48 UTC, jczestochowska submitted a review, later dismissed

2018-04-14 13:48 UTC, jczestochowska commented on scripts/generate_virtual_player.py
> +        for params in range(parameters.shape[0]):
notice than you have a separate variable for expression parameters.shape[0],
if statement is redundant as you use the same distribution both for case when 2 parameters are needed and for the case with 3, you could just use slicing e.g parameters[params][1:] = random.uniform(). Notice also that naming index of array "params" is somewhat misleading for the reader.

2018-04-14 13:48 UTC, jczestochowska commented on scripts/generate_virtual_player.py
> +if __name__=='__main__':
tihs script lacks function that would write as many csv files as there are rows in 'parameters' to seperate directory

2018-04-14 13:48 UTC, jczestochowska commented on scripts/generate_virtual_player.py
> +    return os.path.join(parent_directory, "data", filename)
better to include "data" as parameter, then this function could be moved to data utils and used 'projectwide'

2018-04-14 13:48 UTC, jczestochowska commented on scripts/generate_virtual_player.py
> +    #print(params[0,:][0])
please avoid commented lines as they could be merged accidentally

2018-04-14 13:48 UTC, jczestochowska commented on scripts/generate_virtual_player.py
> +    game.result.to_csv(path, index=False)
you can simply use save_results method from GameSession, then invoking private method _create_result wouldnt be necessary after all it is private for a reason :p

2018-04-14 13:48 UTC, jczestochowska commented on scripts/generate_virtual_player.py
> +    attempt = params[0,:]
attempt is also a misleading name here, why would you create 10 sets of parameters and then use only one? this regards also comment about lacking function for generating multiple csv

2018-04-14 13:48 UTC, jczestochowska commented on scripts/generate_virtual_player.py
> +    return os.path.join(parent_directory, "data", filename)
as for this, method in GameSession named _create_file_path should be rewritten as well

2018-04-23 07:26 UTC, jczestochowska requested changes

2018-04-23 07:26 UTC, jczestochowska commented on scripts/generate_game_sessions.py
> +    make_directory(directory='/Users/karola/PycharmProjects/ZPI/data/virtual_players')
hardcoding paths is not a good idea

2018-04-23 07:26 UTC, jczestochowska commented on scripts/generate_game_sessions.py
> +        # model = RescorlaWagner()
including commented lines not a good idea

2018-04-23 07:26 UTC, jczestochowska commented on scripts/generate_game_sessions.py
> +    make_directory(directory='/Users/karola/PycharmProjects/ZPI/data/virtual_players')
same here

2018-04-27 17:22 UTC, dudamarlena approved these changes

2018-05-16 10:05 UTC, dudamarlena approved these changes

2018-05-28 20:15 UTC, jczestochowska approved these changes

2018-05-28 20:16 UTC, merged